######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 14 23:22:00 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += sql

# Input
SOURCES += main.cpp \
    mainui.cpp \
    dbfacade.cpp

HEADERS += \
    mainui.h \
    dbfacade.h

FORMS += \
    mainui.ui
